export { default as CheckAndDeleteButtons } from './CheckAndDeleteButtons'
export { default as CorrectNumberPosition } from './CorrectNumberPosition'
export { default as GameBoard } from './GameBoard'
export { default as GameScore } from '../../gameScore/GameScore'
export { default as NumberButtons } from './NumberButtons'
export { default as Result } from './Result'
